name: Deploy to Server
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on starting
    steps:
      - name: SSH-SCP-SSH Pipeline
        uses: kangketikonlen/ssh-pipeline@v0.0.3
        with:
          # Remote server hostname or IP address.
          host: ${{ secrets.SSH_HOST }}
          # SSH port on the remote server.
          port: ${{ secrets.SSH_PORT }}
          # SSH username for the remote server.
          user: ${{ secrets.SSH_USER }}
          # SSH private key to authenticate. (Use GitHub secrets!)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Multiline block of commands to run before the SCP transfer.
          first_ssh: |
            cd ITORO-Tube
            git pull
