name: Deploy to Server
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy on starting
    steps:
      - name: SSH-SCP-SSH Pipeline
        uses: kangketikonlen/ssh-pipeline@v0.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          first_ssh: |
            cd ITORO-Tube
            git pull
            docker compose exec php sh -c "cd tube && composer install"
            docker compose exec php sh -c "cd tube && npm install"
            docker compose exec php sh -c "cd tube && php artisan migrate"
            docker compose exec php sh -c "cd tube && npm run build"
            docker compose exec php sh -c "cd tube && php artisan cache:clear"
            docker compose exec php sh -c "cd tube && php artisan config:cache"
            docker compose exec php sh -c "cd tube && php artisan route:cache"

